### ISSUE TITLE
plugin_wirelessnetworkkeys.zip has virus or malware

### ISSUE THREAD

**Issue by jwsmith601** [builtbybel/CloneApp#8]
After downloading, I get message that plugin_wirelessnetworkkeys.zip has virus or malware

**Comment by Belim** [comment]
It's not my app and ONLY an external Plug-in from Nir Sofer. Half of its apps are incorrectly flagged > False positives!
https://www.nirsoft.net/false_positive_report.html

**Comment by jwsmith601** [comment]
Sorry for my late Close on this - was (& am) new to Github

**Comment by n8wachT** [comment]
However, still carefull. I got severe warning about ransomware in dowloads of the themes (.zip)
